<a href="https://colab.research.google.com/github/neerajgoud23/100-of-Machine_learning-/blob/main/day7_pytorch_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


In [2]:
if torch.cuda.is_available():
  print("gpu is available")
  print(f"usiung gpu:{torch.cuda.get_device_name(0)}")
else:
  print("gpu is not available using CPU")

gpu is available
usiung gpu:Tesla T4


In [3]:
A  = torch.empty(2,3)
type(A)

torch.Tensor

In [4]:
torch.zeros(2,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [5]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [6]:
torch.rand(1,100)

tensor([[0.1499, 0.3438, 0.8773, 0.4210, 0.3773, 0.0079, 0.9359, 0.0095, 0.2373,
         0.8424, 0.9006, 0.7900, 0.2521, 0.2821, 0.9102, 0.6131, 0.1868, 0.3590,
         0.1275, 0.7742, 0.7002, 0.7089, 0.4478, 0.1984, 0.9739, 0.7909, 0.3459,
         0.2251, 0.4889, 0.3945, 0.4873, 0.9208, 0.2835, 0.5139, 0.4185, 0.6050,
         0.0542, 0.1819, 0.0879, 0.4470, 0.3792, 0.5556, 0.5547, 0.4690, 0.3569,
         0.1736, 0.8770, 0.3468, 0.1147, 0.2997, 0.9604, 0.2072, 0.6043, 0.3365,
         0.1472, 0.5005, 0.3950, 0.5534, 0.2905, 0.0795, 0.0343, 0.1919, 0.4584,
         0.9682, 0.3731, 0.0429, 0.2240, 0.3381, 0.1033, 0.6919, 0.1631, 0.2794,
         0.8561, 0.1179, 0.1235, 0.4952, 0.9542, 0.0279, 0.8511, 0.6941, 0.0741,
         0.4156, 0.1188, 0.7998, 0.6819, 0.2420, 0.9252, 0.6932, 0.3889, 0.6584,
         0.8385, 0.7552, 0.5726, 0.8592, 0.0129, 0.4119, 0.4450, 0.9104, 0.4373,
         0.2336]])

In [7]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [8]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [10]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [11]:
torch.linspace(0,10,10
               )

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [12]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [13]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
x.shape

torch.Size([2, 3])

In [16]:
torch.empty_like(x)

tensor([[3616445622929465956, 6068092717709143349, 3689075032085640241],
        [6499879781519145006, 7309453675965983778, 8315168162784306286]])

In [18]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [19]:
x.dtype


torch.int64

In [21]:
x = torch.tensor([1.0,2.0,3,0],dtype=torch.int32)

x

tensor([1, 2, 3, 0], dtype=torch.int32)

In [22]:
x.to(torch.float32)

tensor([1., 2., 3., 0.])

#Mathematical Operations


In [23]:
x = torch.rand(2,2)
x+2

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])

In [24]:
x-2

tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])

In [25]:
x*3


tensor([[2.1353, 2.3627],
        [1.2549, 2.7042]])

In [26]:
x//4

tensor([[0., 0.],
        [0., 0.]])

In [27]:
((x*100)/4)

tensor([[17.7941, 19.6895],
        [10.4576, 22.5354]])

In [28]:
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

In [29]:
c = torch.tensor([1, -2, 3, -4])

In [30]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [31]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [32]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [33]:
print(torch.ceil(d))
print(torch.floor(d))

tensor([2., 3., 4., 5.])
tensor([1., 2., 3., 4.])


In [34]:
e = torch.randint(size=(3,2),low=0,high=10,dtype=torch.float32)

In [35]:
e

tensor([[1., 0.],
        [4., 3.],
        [8., 7.]])

In [36]:
torch.sum(e)

tensor(23.)

In [37]:
torch.sum(e,dim=0)

tensor([13., 10.])

In [38]:
print("mean:",torch.mean(e))
print("median:",torch.median(e))
print("min:",torch.min(e))
print("max:",torch.max(e))
print("product:",torch.prod(e))
print("standard deviation:",torch.std(e))
print("variancce:",torch.var(e))
print("argmax:",torch.argmax(e))
print("argmin:",torch.argmin(e))

mean: tensor(3.8333)
median: tensor(3.)
min: tensor(0.)
max: tensor(8.)
product: tensor(0.)
standard deviation: tensor(3.1885)
variancce: tensor(10.1667)
argmax: tensor(4)
argmin: tensor(1)


# Matrix Multiplication


In [39]:
a = torch.randint(size=(3,2),low=0,high=10)
b = torch.randint(size=(2,3),low=0,high=10)
print(a)
print(b)

tensor([[4, 6],
        [0, 1],
        [9, 9]])
tensor([[8, 0, 7],
        [0, 0, 9]])


In [40]:
c = torch.matmul(a,b)
print(c)

tensor([[ 32,   0,  82],
        [  0,   0,   9],
        [ 72,   0, 144]])


In [41]:
torch.transpose(c,0,1)

tensor([[ 32,   0,  72],
        [  0,   0,   0],
        [ 82,   9, 144]])

In [45]:
d = torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
torch.det(d)


tensor(-86.0000)

In [58]:
e = torch.randint(size=(3,2),low=0,high=10,dtype=torch.float32)
e

tensor([[7., 8.],
        [3., 6.],
        [1., 5.]])

In [59]:
torch.log(e)

tensor([[1.9459, 2.0794],
        [1.0986, 1.7918],
        [0.0000, 1.6094]])

In [60]:
torch.exp(e)

tensor([[1.0966e+03, 2.9810e+03],
        [2.0086e+01, 4.0343e+02],
        [2.7183e+00, 1.4841e+02]])

In [55]:
torch.sigmoid(e)

tensor([[0.9999, 0.9991],
        [0.9999, 0.8808],
        [0.9975, 0.9991]])

In [61]:
torch.softmax(e, dim=1)

tensor([[0.2689, 0.7311],
        [0.0474, 0.9526],
        [0.0180, 0.9820]])

In [62]:
torch.relu(e)

tensor([[7., 8.],
        [3., 6.],
        [1., 5.]])